### ISSUE TITLE
Question about realignment_forward.py

### ISSUE THREAD

**Issue by ynzhou18** [Zhe-jiang/PRAISE#5]
Hi, I used this command to do realignment, but get this error showed as follows. Can you give me some answer? Thank you!
My command is "python3.8 realignment_forward.py --fast -t 10 -ms 3 -x ~/1_data/1_genome_and_other_db/hg38_Genome_UCSC/DB/hisat2_maxLenTrans_and_rRNA/hg38.6rRNA_new.no45S.fa -i test.sort.map.sort.bam -o test.new.bam -f test.new.filter.bam".

Traceback (most recent call last):
  File "realignment_forward.py", line 1121, in <module>
    bam_output_all = bam_merge(temp_out_file[ii], bam_output_all)
  File "realignment_forward.py", line 732, in bam_merge
    temp_bam_input = pysam.AlignmentFile(temp_bam, "rb")
  File "pysam/libcalignmentfile.pyx", line 747, in pysam.libcalignmentfile.AlignmentFile.__cinit__
  File "pysam/libcalignmentfile.pyx", line 946, in pysam.libcalignmentfile.AlignmentFile._open
FileNotFoundError: [Errno 2] could not open alignment file `tmp_3wXkpiVc_test.sort.map.sort.bam/test.sort.map.sort.temp.1.realign.bam`: No such file or directory

**Comment by MZNOTE** [comment]
same question

**Comment by Jarvis559** [comment]
same question

**Comment by MZNOTE** [comment]
我是建航，你的邮件已经收到，辛苦了！

**Comment by Jarvis559** [comment]
Did you solve the problem, please?

**Comment by Zhe-jiang** [comment]
Hi, thank you for using our methods.
Normally, this error is caused by the errors during reading and processing your input BAM file. Please check your BAM file again and make sure it is sorted by name instead of by index.

Hope this will solve your problem.
